### ISSUE TITLE
Kernel module not loading in El Capitan

### ISSUE THREAD

**Issue by gegles** [sctplab/SCTP_NKE_Yosemite#12]
Here is what I get when trying to load the module:

➜  ~  sudo kextutil /System/Library/Extensions/SCTP.kext
Diagnostics for /System/Library/Extensions/SCTP.kext:
Code Signing Failure: not code signed
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/System/Library/Extensions/SCTP.kext"
(kernel) kxld[org.sctp.nke.SCTP]: In interface org.sctp.kpi.sctpsupport of **kernel**, couldn't find symbol _nd_ifinfo

(kernel) kxld[org.sctp.nke.SCTP]: In interface org.sctp.kpi.sctpsupport of **kernel**, couldn't find symbol _nd_ifinfo_indexlim

(kernel) kxld[org.sctp.nke.SCTP]: The following symbols are unresolved for this kext:
(kernel) kxld[org.sctp.nke.SCTP]:   _nd_ifinfo
(kernel) kxld[org.sctp.nke.SCTP]:   _nd_ifinfo_indexlim
(kernel) Can't load kext org.sctp.nke.SCTP - link failed.
(kernel) Failed to load executable for kext org.sctp.nke.SCTP.
(kernel) Kext org.sctp.nke.SCTP failed to load (0xdc008016).
(kernel) Failed to load kext org.sctp.nke.SCTP (error 0xdc008016).
Failed to load /System/Library/Extensions/SCTP.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).

**Comment by tuexen** [comment]
This is a know issue and will not be resolved for SCTP_NKE_Yosemite. Expect a SCTP_NKE_ElCapitan to show up once Apple releases the source code of it and I got it running.

**Comment by tuexen** [comment]
Please have a look at [SCTP NKE for El Capitan](https://github.com/sctplab/SCTP_NKE_ElCapitan).
