### ISSUE TITLE
SHUTDOWN-ACK-Chunk with invalid length is not silently discarded

### ISSUE THREAD

**Issue by TheAomx** [sctplab/SCTP_NKE_Yosemite#16]
See the following testcase for more info:
https://github.com/nplab/misc-sctp-testscripts/blob/master/sctp-invalid-length-tests/sctp-invalid-shutdown-ack-invalid-too-long-length.pkt

**Comment by tuexen** [comment]
Fixed.

**Comment by tuexen** [comment]
Fixed.
