### ISSUE TITLE
KPI issue. Kext not loading due to unresolved symbols KXLD freaking out 

### ISSUE THREAD

**Issue by bigkahuna666** [sctplab/SCTP_NKE_Yosemite#18]
I am trying to get a kext loaded for a fusion-io (ioDrive II) card. The kext was originally from the Yosemite bundle that SanDisk (at the time maybe even still Fusion-io themselves?) released. Now I am trying to make it load on ElCapitan. The bundle installs fine and after compulsory restart I end up with a kext in my Extensions folder. The problem is it doesn't load! Here is what terminal tells me:

sh-3.2# kextutil -t /System/Library/Extensions/iomemory-vsl.kext 
Notice: /System/Library/Extensions/iomemory-vsl.kext has debug properties set.
Diagnostics for /System/Library/Extensions/iomemory-vsl.kext:
Code Signing Failure: not code signed
kext-dev-mode allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/System/Library/Extensions/iomemory-vsl.kext"
kext signature failure override allowing invalid signature -67062 0xFFFFFFFFFFFEFA0A for kext "/System/Library/Extensions/iomemory-vsl.kext"
(kernel) kxld[com.fusionio.driver.iomemory-vsl]: The following symbols are unresolved for this kext:
(kernel) kxld[com.fusionio.driver.iomemory-vsl]: 	__ZN8IOMapper11NewARTTableEyPPvPj
(kernel) kxld[com.fusionio.driver.iomemory-vsl]: 	__ZN8IOMapper12FreeARTTableEP6OSDatay
(kernel) Can't load kext com.fusionio.driver.iomemory-vsl - link failed.
(kernel) Failed to load executable for kext com.fusionio.driver.iomemory-vsl.
(kernel) Kext com.fusionio.driver.iomemory-vsl failed to load (0xdc008016).
(kernel) Failed to load kext com.fusionio.driver.iomemory-vsl (error 0xdc008016).
Failed to load /System/Library/Extensions/iomemory-vsl.kext - (libkern/kext) link error.
Check library declarations for your kext with kextlibs(8).
sh-3.2# kextlibs /System/Library/Extensions/iomemory-vsl.kext 
For all architectures:
    com.apple.iokit.IOStorageFamily = 2.1
    com.apple.kpi.bsd = 15.6
    com.apple.kpi.iokit = 15.6
    com.apple.kpi.libkern = 15.6
    com.apple.kpi.mach = 15.6

For x86_64:
    11 symbols not found in any library kext.

It looks like it could be an easy fix? I am by no means an expert, but I am sure there must be a way? Any suggestions/help would be much appreciated.

**Comment by tuexen** [comment]
Is there any relation to the SCTP.kext this repo is about? If you have problems with a different kext, please contact the vendor of it.

**Comment by bigkahuna666** [comment]
Whoops. Rooki error. Just realised I posted this in the wrong section. Only just signed up with GitHub this morning :)
